apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus:latest
          env:
          - name: MAX_HEAP
            value: "800m"
          - name: MIN_HEAP
            value: "300m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-storage
              mountPath: /sonatype-work
    volumes:
      - name: nexus-storage
        persistentVolumeClaim:
          claimName: nexus-data 



            
             
 
