name: docker-deploy
on:
  push:
    branches:
      - main
jobs:
  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth activate-service-account 547531375627-compute@developer.gserviceaccount.com --key-file=constant-rig-322310-a22e6ede85c7.json
        gcloud auth configure-docker
        docker build . --file Dockerfile --tag my-image-name:v1
        docker tag my-image-name:v1 gcr.io/constant-rig-322310/my-image-name:v1
        docker push gcr.io/constant-rig-322310/my-image-name:v1