name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login -u _json_key -p  "${{ secrets.GCS_SA_KEY }}" https://gcr.io
        docker build . --file Dockerfile --tag my-image-name:v1
        docker tag my-image-name:v1 gcr.io/constant-rig-322310/my-image-name:v1
        docker push gcr.io/constant-rig-322310/my-image-name:v1