name: cloudrun-deploy
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # Setup gcloud CLI
    - uses: actions/checkout@v1
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCS_SA_KEY}}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
        docker build . --file Dockerfile --tag my-image-name:v1
        docker tag my-image-name:v1 gcr.io/constant-rig-322310/my-image-name:v1
        docker push gcr.io/constant-rig-322310/my-image-name:v1