name: docker-deploy
on:
  push:
    branches:
      - main
jobs:
  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: login  
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        branch: main
        github_token: ${{ secrets.HUB_TOKEN }}
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.FILE }}
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker --quiet
        docker build . --file Dockerfile --tag my-image-name:latest
        docker tag my-image-name:latest gcr.io/constant-rig-322310/my-image-name:v1
        docker push gcr.io/constant-rig-322310/my-image-name:v1