name: docker-deploy
on:
  push:
    branches:
      - main
jobs:
  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # Configure Docker with Credentials
    - name: Configure Docker
      shell: bash
      env:
        key : ${{secrets.FILE}}
      run: |
        echo $key >> key.json
        cat key.json
        echo ${{secrets.PROJECT}}
        gcloud auth activate-service-account ${{secrets.GCP_EMAIL}} --key-file=key.json
        gcloud auth configure-docker 
        docker build . --file Dockerfile --tag my-image-name:latest
        docker tag my-image-name:latest gcr.io/ ${{secrets.PROJECT}} /my-image-name:v1
        docker push gcr.io/ ${{secrets.PROJECT}} /my-image-name:v1